CREATE TABLE Item(
ItemID INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(255),
Description NVARCHAR(1000),
UnitCost DECIMAL DEFAULT 0.00
)

CREATE TABLE OrderItem(
OrderItemID INT IDENTITY(1,1) PRIMARY KEY,
ItemID INT REFERENCES Item(ItemID),
Quantity INT
)

CREATE TABLE [Order](
OrderID INT IDENTITY(1,1) PRIMARY KEY,
CustomerID INT, 
OrderDate DATETIME
)

CREATE TABLE OrderStatus(
OrderStatusID INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(255)
)

CREATE TABLE Address(
AddressID INT IDENTITY(1,1) PRIMARY KEY,
Street NVARCHAR(255),
Country NVARCHAR(255) DEFAULT 'Canada',
Province NVARCHAR(255) DEFAULT 'ON',
PostalCode NVARCHAR(255)
)

CREATE TABLE Invoice(
InvoiceID INT IDENTITY(1,1) PRIMARY KEY,
OrderID INT REFERENCES [Order](OrderID),
AddressID INT REFERENCES Address(AddressID),
SubTotal DECIMAL,
Total AS (SubTotal*1.13)
)